# Generated by Django 4.2.1 on 2023-05-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajeros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='hotel',
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=128)),
                ('hotel', models.ManyToManyField(to='Viajeros.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='hotel',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
